# Generated by Django 4.1.6 on 2023-02-22 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avatar',
            name='image',
            field=models.ImageField(blank=True, default='min/static/main/img/noPhoto.jpg', null=True, upload_to=''),
        ),
    ]
